title = "MaxOutNet Phoneme Classifier"

[CONSTANTS]
DTYPE = "mfcc"
SAMPLE_RATE = 16000
HOP_SIZE = 512
N_FFT = 2048
N_MFCC = 20
N_MELS = 128

[PATHS]
TIMIT_PATH = '/media/dataset/bach-TIMIT/LDC93S1-TIMIT/'
PREPROCESSED_DATA_PATH = '/media/dataset/TIMIT_preprocessed_39'
PHONESET_61 = 'timit61.phoneset'
PHONESET_39 = 'timit39.phoneset'

[HPARAMS]
dataset_name = "Timit"

batch_size = 64
learning_rate = 0.0003
max_epoch = 10000
validation_interval = 10
checkpoint_interval = 10

chunk_len = 1  # in seconds

decay_steps = 10000
decay_rate = 0.97

resume = false  # zero if train new model.

num_labels = 39  # 61 or 39

model_name = "MaxOutNet"
input_height = 20

device = "cuda"

seed = -1  # -1 for random seed.